# anomaly-service(이상감지) 테스트

name: Anomaly Service CI

on:
  pull_request:
    branches:
      - develop
    paths:
      - 'anomaly-service/**'

permissions:
  contents: read

jobs:
  docker-build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./anomaly-service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test Docker Build (Dry Run)
        uses: docker/build-push-action@v5
        with:
          context: ./anomaly-service
          # push를 false로 설정하여 ECR에 올리지 않고 빌드 성공 여부만 확인
          push: false 
          tags: windfarm-onm-anomaly:ci-test
          cache-from: type=gha
          cache-to: type=gha,mode=max

